/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package apotek;

import java.awt.Cursor;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import main.MainForm;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author faheem
 */
public class FrmRptKeuangan extends javax.swing.JInternalFrame {
    private Connection conn;
    
    /**
     * Creates new form FrmRptKeuangan
     */
    public FrmRptKeuangan() {
        initComponents();
        jList1.setSelectedIndex(0);
    }
    
    public void setConn(Connection c){
        this.conn=c;
    }
    
    private void udfPreview(){
        HashMap reportParam = new HashMap();
        JasperReport jasperReport = null;
        try {
            reportParam.put("corporate", MainForm.sNamaUsaha); 
            reportParam.put("alamat", MainForm.sAlamat);
            reportParam.put("telp", MainForm.sTelp);
            reportParam.put("tanggal1", new SimpleDateFormat("yyyy-MM-dd").format(jxDateFrom.getDate()));
            reportParam.put("tanggal2", new SimpleDateFormat("yyyy-MM-dd").format(jxDateTo.getDate()));
            reportParam.put("item", "");

            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            String sReport="";
            switch(jList1.getSelectedIndex()){
                case 0:{sReport="PenjualanDetailProfit"; break;}
                case 1:{sReport="PenjualanRekapProfit"; break;}
                case 2:{sReport="PenjualanRekapProfitPerHari"; break;}
                case 3:{sReport="GR_Discount"; break;}

            }
            jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResourceAsStream("Reports/"+sReport+".jasper"));

            if(sReport.length()==0) {
                setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                return;
            }
            JasperPrint print = JasperFillManager.fillReport(jasperReport, reportParam, conn);
            
            print.setOrientation(jasperReport.getOrientationValue());
            if (print.getPages().isEmpty()) {
                setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
                return;
            }
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            JasperViewer.viewReport(print, false);

        } catch (JRException ex) {
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jxDateTo = new org.jdesktop.swingx.JXDatePicker();
        jxDateFrom = new org.jdesktop.swingx.JXDatePicker();
        btnPreview = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setClosable(true);
        setTitle("Laporan Keuangan");
        getContentPane().setLayout(null);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1.  Detail Profit per Transaksi Penjualan & Retur", "2.  Rekap Profit per Transaksi Penjualan & Retur", "3.  Rekap Profit Penjualan Per Hari", "4.  Rekap Diskon Per Tanggal" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 5, 335, 305);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter"));
        jPanel2.setLayout(null);

        jLabel3.setText("Sampai : ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(15, 65, 65, 25);

        jLabel4.setText("Dari : ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(15, 35, 65, 25);
        jPanel2.add(jxDateTo);
        jxDateTo.setBounds(90, 65, 175, 23);

        jxDateFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxDateFromActionPerformed(evt);
            }
        });
        jPanel2.add(jxDateFrom);
        jxDateFrom.setBounds(90, 35, 175, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(350, 10, 275, 300);

        btnPreview.setText("Tampilkan");
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreview);
        btnPreview.setBounds(395, 310, 110, 27);

        btnClose.setText("Tutup");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(506, 310, 110, 27);

        setBounds(0, 0, 644, 377);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        udfPreview();
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void jxDateFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxDateFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jxDateFromActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPreview;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jxDateFrom;
    private org.jdesktop.swingx.JXDatePicker jxDateTo;
    // End of variables declaration//GEN-END:variables
}
