/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.klinik.panel;

/**
 *
 * @author faheem
 */
public class PanelRegInfo extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegInfo
     */
    public PanelRegInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAlergi = new javax.swing.JTextField();
        txtAlergi1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Alergi :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 75, 20));

        txtAlergi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAlergi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAlergi.setEnabled(false);
        add(txtAlergi, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 10, 240, 22));

        txtAlergi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAlergi1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAlergi1.setEnabled(false);
        add(txtAlergi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 10, 240, 22));

        jLabel2.setText("Alergi :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 75, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAlergi;
    private javax.swing.JTextField txtAlergi1;
    // End of variables declaration//GEN-END:variables
}
