/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apotek.master;

import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import main.GeneralFunction;
import main.MainForm;

/**
 *
 * @author cak-ust
 */
public class FrmDiskonEvent extends javax.swing.JInternalFrame {
    GeneralFunction fn=new GeneralFunction();
    /**
     * Creates new form FrmDiskonEvent
     */
    public FrmDiskonEvent() {
        initComponents();
        jTable1.setRowHeight(20);
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(new MyRowRenderer());
        }
        
        jXDateAwal.setFormats("dd/MM/yyyy");
        jXDateAkhir.setFormats("dd/MM/yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jXDateAkhir = new org.jdesktop.swingx.JXDatePicker();
        jXDateAwal = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Diskon & Promo - Event");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mulai", "Sampai", "Tipe Tarif", "Tipe Diskon", "Item", "Minimum Bill", "Disc %", "Disc Rp", "Aktif", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 65, 715, 210));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Periode"));
        jPanel1.setLayout(null);

        jLabel1.setText("Sampai");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(215, 20, 70, 20);

        jLabel2.setText("Dari");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 20, 70, 20);
        jPanel1.add(jXDateAkhir);
        jXDateAkhir.setBounds(275, 20, 125, 22);
        jPanel1.add(jXDateAwal);
        jXDateAwal.setBounds(65, 20, 125, 20);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(445, 20, 120, 23);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, 715, 55));

        jPanel3.setLayout(null);

        jButton2.setText("Baru");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(10, 10, 120, 23);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel3.add(btnHapus);
        btnHapus.setBounds(130, 10, 105, 23);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 280, 715, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        udfLoadData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        addItem();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        udfLoadData();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row=jTable1.getSelectedRow();
        if(row>=0 && JOptionPane.showConfirmDialog(this, "Anda yakin untuk menghapus promo/ diskon ini? ", "Hapus promo", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            Integer id=fn.udfGetInt(jTable1.getValueAt(row, jTable1.getColumnModel().getColumnIndex("Id")));
            try {
                int i=MainForm.conn.createStatement().executeUpdate("delete from event_diskon where id="+id);
                if(i>0){
                    udfLoadData();
                }
            } catch (SQLException ex) {
                Logger.getLogger(FrmDiskonEvent.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDateAkhir;
    private org.jdesktop.swingx.JXDatePicker jXDateAwal;
    // End of variables declaration//GEN-END:variables

    SimpleDateFormat ymd=new SimpleDateFormat("yyyy-MM-dd");
    private void udfLoadData() {
        try {
            String query="select d.id, d.tipe_tarif, d.tipe_diskon, d.tgl_mulai, d.tgl_sampai, d.aktif, coalesce(i.item_name,'') as item_name, \n" +
                        "coalesce(d.min_tot_bill,0) as min_tot_bill, coalesce(d.diskon_persen,0) as diskon_persen, coalesce(d.diskon_rp,0) as diskon_rp, \n" +
                        "coalesce(d.keterangan,'') as keterangan\n" +
                        "from event_diskon d\n" +
                        "left join barang i on i.item_code=d.item_code\n" +
                        "where to_char(d.tgl_mulai, 'yyyy-MM-dd')>='"+ymd.format(jXDateAwal.getDate())+"'\n" +
                        "and to_char(d.tgl_mulai, 'yyyy-MM-dd')<='"+ymd.format(jXDateAkhir.getDate())+"' "+
                        "order by d.tgl_mulai" ;
            ((DefaultTableModel)jTable1.getModel()).setNumRows(0);
            ResultSet rs=MainForm.conn.createStatement().executeQuery(query);
            while(rs.next()){
                ((DefaultTableModel)jTable1.getModel()).addRow(new Object[]{
                    rs.getDate("tgl_mulai"),
                    rs.getDate("tgl_sampai"),
                    rs.getString("tipe_tarif"),
                    rs.getString("tipe_diskon"),
                    rs.getString("item_name"),
                    rs.getDouble("min_tot_bill"),
                    rs.getDouble("diskon_persen"),
                    rs.getDouble("diskon_rp"),
                    rs.getBoolean("aktif"),
                    rs.getInt("id")
                });
            }
            rs.close();
            if(jTable1.getRowCount()>0){
                jTable1.setRowSelectionInterval(0, 0);
                fn.autoColWidthTable(jTable1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmDiskonEvent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void addItem(){
        DlgDiskonEvent d1=new DlgDiskonEvent(JOptionPane.getFrameForComponent(this), true);
        d1.setLocationRelativeTo(null);
        d1.setTitle("Tambah Even Diskon");
        d1.setVisible(true);
        udfLoadData();
    }
    
    public class MyRowRenderer extends DefaultTableCellRenderer implements TableCellRenderer{
        SimpleDateFormat dmyFmt=new SimpleDateFormat("dd/MM/yyyy");

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            if(value instanceof Date ){
                value=dmyFmt.format(value);
            }else if(value instanceof Double ||value instanceof Integer ||value instanceof Float  ){
                setHorizontalAlignment(SwingConstants.RIGHT);
                value=fn.dFmt.format(value);
            }
            setFont(table.getFont());
            if(isSelected){
                setBackground(table.getSelectionBackground());
                setForeground(table.getSelectionForeground());
            }else{
                setBackground(table.getBackground());
                setForeground(table.getForeground());
            }

            setValue(value);
            return this;
        }
    }

    
}
