/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author faheem
 */
public class FrmDlgMenuGroup extends javax.swing.JDialog {
    private Connection conn;
    private String oldId="";
    
    /**
     * Creates new form FrmDlgMenuGroup
     */
    public FrmDlgMenuGroup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setConn(Connection c){
        this.conn=c;
    }
    
    private void setMenuGroup(String id, String ket){
        this.oldId=id;
        txtID.setText(id);
        txtKeterangan.setText(ket);
    }
    
    private void simpan() throws SQLException{
        if(!cekSebelumSimpan())
            return;
        if(oldId.length() > 0){ //update
            String sUpd="UPDATE m_menu_group\n" +
                    "   SET group_id=?, keterangan=?, module_name=?\n" +
                    " WHERE group_id=?;";
            PreparedStatement ps=conn.prepareStatement(sUpd);
            ps.setString(1, txtID.getText());
            ps.setString(2, txtKeterangan.getText());
            ps.setString(3, "APOTEK");
            ps.setString(3, oldId);
            ps.execute();
        }
        else{ //update
            String sUpd="INSERT INTO m_menu_group(\n" +
            "            group_id, keterangan, module_name)\n" +
            "    VALUES (?, ?, ?);";
            PreparedStatement ps=conn.prepareStatement(sUpd);
            ps.setString(1, txtID.getText());
            ps.setString(2, txtKeterangan.getText());
            ps.setString(3, "APOTEK");
            
            ps.execute();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Keterangan : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(15, 40, 85, 25);

        jLabel2.setText("Group ID : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(15, 10, 85, 25);
        getContentPane().add(txtKeterangan);
        txtKeterangan.setBounds(110, 40, 425, 30);
        getContentPane().add(txtID);
        txtID.setBounds(110, 10, 235, 30);

        btnSave.setText("Simpan");
        getContentPane().add(btnSave);
        btnSave.setBounds(340, 80, 95, 27);

        btnCancel.setText("Batal");
        getContentPane().add(btnCancel);
        btnCancel.setBounds(440, 80, 95, 27);

        setBounds(0, 0, 562, 147);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDlgMenuGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDlgMenuGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDlgMenuGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDlgMenuGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDlgMenuGroup dialog = new FrmDlgMenuGroup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtKeterangan;
    // End of variables declaration//GEN-END:variables

    private boolean cekSebelumSimpan() {
        btnSave.requestFocusInWindow();
        if(txtID.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Masukkan ID terlebih dulu!");
            txtID.requestFocus();
            return false;
        }
        if(txtKeterangan.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Masukkan Keterangan terlebih dulu!");
            txtKeterangan.requestFocus();
            return false;
        }
        
        return true;
    }
}
