/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.klinik.rm;

import apotek.Main;
import com.klinik.dao.PasienDao;
import com.klinik.model.Pasien;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import main.GeneralFunction;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author cak-ust
 */
public class DlgLookupPasien extends javax.swing.JDialog {
    private GeneralFunction fn=new GeneralFunction();
    Pasien selectedPasien=null;
    private Object srcForm;
    /**
     * Creates new form DlgLookupPasien
     */
    public DlgLookupPasien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        PromptSupport.setPrompt("Masukan kata pencarian minimal 3 karakter", jTextField1);
        setTitle("Lookup Pasien");
    }

    public void setVisibleButtonPilih(boolean  b){
        btnPilih.setVisible(b);
    }
    
    private void udfFilter(){
        String query="select norm, nama, case when jenis_kelamin='L' then 'Laki-laki' else 'Perempuan' end as jenis_kelamin, \n" +
                    "coalesce(alamat_domisili,'') as alamat_domisili, tgl_lahir, \n" +
                    "extract('year' from age(current_date, tgl_lahir))||' Th, '||extract('month' from age(current_date, tgl_lahir))||' Bln' as usia\n" +
                    "from rm_pasien "
                + "where norm||nama||coalesce(alamat_domisili,'')||to_char(tgl_lahir, 'dd-MM-yyyy') ilike '%"+jTextField1.getText()+"%' "
                + "order by nama, jenis_kelamin";
        
        try {
            ((DefaultTableModel)jXTable1.getModel()).setNumRows(0);
            ResultSet rs=Main.conn.createStatement().executeQuery(query);
            while(rs.next()){
                ((DefaultTableModel)jXTable1.getModel()).addRow(new Object[]{
                    rs.getString("norm"),
                    rs.getString("nama"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("alamat_domisili"),
                    rs.getDate("tgl_lahir"),
                    rs.getString("usia"),
                });
            }
            if(jXTable1.getRowCount()>0){
                jXTable1.setRowSelectionInterval(0, 0);
                fn.autoColWidthTable(jXTable1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DlgLookupPasien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public Pasien getSelectedPasien(){
        return this.selectedPasien;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnPilih = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("FIlter"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, 275, 22));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/small/refresh.png"))); // NOI18N
        jButton1.setText("Refresh");
        jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 15, 100, 25));

        btnPilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/small/accept.png"))); // NOI18N
        btnPilih.setText("Pilih");
        btnPilih.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 15, 125, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 605, 55));

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Norm", "Nama", "Jenis Kelamin", "Alamat", "Tgl Lahir", "Usia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jXTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 70, 600, 250));

        setBounds(0, 0, 634, 362);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        udfFilter();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            udfFilter();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
        int iRow=jXTable1.getSelectedRow();
        if(iRow<0){
            return;
        }
        this.selectedPasien=new PasienDao().getPasien(jXTable1.getValueAt(iRow, jXTable1.getColumnModel().getColumnIndex("Norm")).toString());
        this.dispose();
    }//GEN-LAST:event_btnPilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgLookupPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgLookupPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgLookupPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgLookupPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgLookupPasien dialog = new DlgLookupPasien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPilih;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables

    void setSrcForm(Object aThis) {
        this.srcForm=aThis;
    }

}