/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.klinik.rm;

import com.klinik.dao.PasienDao;
import com.klinik.dao.ReservasiDao;
import com.klinik.model.Pasien;
import com.klinik.model.Reservasi;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author faheem
 */
public class DlgPasien extends javax.swing.JDialog {
    private Object srcForm;
    private Date tglReservasi;
    private Pasien selectedPasien=null;
    
    /**
     * Creates new form NewJDialog
     */
    public DlgPasien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Pasien getSelectedPasien(){
        return this.selectedPasien;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNorm = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        txtTglLahir = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTempatLahir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHp = new javax.swing.JTextField();
        txtUsiaTh = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUsiaBl = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbSex = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txtNamaKeluarga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTelpKeluarga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Pasien");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 250, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NORM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 75, 20));

        txtNorm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNorm.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNorm.setEnabled(false);
        jPanel1.add(txtNorm, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 10, 70, 22));

        txtNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 35, 325, 22));

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 75, 20));

        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 95, 20));

        txtAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 135, 325, 22));

        jLabel4.setText("Telp");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 95, 20));

        txtTelepon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 160, 95, 22));

        txtTglLahir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtTglLahir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtTglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 85, 105, 22));

        jLabel5.setText("Jenis Kelamin : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 110, 20));

        jLabel6.setText("Tmp. Lahir : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 105, 20));

        txtTempatLahir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtTempatLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 60, 160, 22));

        jLabel7.setText("HP");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 160, 70, 20));

        txtHp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 160, 145, 22));

        txtUsiaTh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtUsiaTh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtUsiaTh, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 85, 50, 22));

        jLabel8.setText("Th");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 85, 35, 20));

        jLabel9.setText("Usia");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 85, 35, 20));

        jLabel10.setText("Bln");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 85, 35, 20));

        txtUsiaBl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtUsiaBl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtUsiaBl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 85, 50, 22));

        jLabel11.setText("Tgl. Lahir");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 95, 20));

        cmbSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-laki", "Perempuan" }));
        jPanel1.add(cmbSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 130, -1));

        jLabel12.setText("Nama Keluarga ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, 120, 20));

        txtNamaKeluarga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtNamaKeluarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 185, 325, 22));

        jLabel13.setText("Telp. Keluarga ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 20));

        txtTelpKeluarga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtTelpKeluarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 210, 325, 22));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/small/find.png"))); // NOI18N
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 30, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 470, 245));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icon/32/cd.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 285, 120, -1));

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Icon/32/close.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 285, 105, -1));

        setBounds(0, 0, 502, 371);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DlgLookupPasien d1=new DlgLookupPasien(JOptionPane.getFrameForComponent(this), true);
        d1.setVisible(true);
        Pasien px=d1.getSelectedPasien();
        if(px !=null){
            txtNorm.setText(px.getNorm());
            txtNama.setText(px.getNama());
            txtAlamat.setText(px.getAlamatDomisili());
            cmbSex.setSelectedIndex(px.getJenisKelamin().equalsIgnoreCase("L")? 0: 1);
            txtTempatLahir.setText(px.getTempatLahir());
            txtTglLahir.setText(new SimpleDateFormat("dd-MM-yyyy").format(px.getTanggalLahir()));
            txtTelepon.setText(px.getTelepon());
            txtHp.setText(px.getHp());
            txtNamaKeluarga.setText(px.getNamaKeluarga());
            txtTelpKeluarga.setText(px.getTeleponKeluarga());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        udfSave();

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPasien dialog = new DlgPasien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cmbSex;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtHp;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaKeluarga;
    private javax.swing.JTextField txtNorm;
    private javax.swing.JTextField txtTelepon;
    private javax.swing.JTextField txtTelpKeluarga;
    private javax.swing.JTextField txtTempatLahir;
    private javax.swing.JFormattedTextField txtTglLahir;
    private javax.swing.JFormattedTextField txtUsiaBl;
    private javax.swing.JFormattedTextField txtUsiaTh;
    // End of variables declaration//GEN-END:variables
    
    private boolean udfCekBeforeSave(){
        btnSimpan.requestFocusInWindow();
        if(txtNama.getText().trim().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Silahkan isi nama terlebih dulu!");
            txtNama.requestFocus();
            return false;
        }
        if(txtAlamat.getText().trim().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Silahkan isi alamat terlebih dulu!");
            txtAlamat.requestFocus();
            return false;
        }
        return true;
    }
    
    private void udfSave() {
        if(!udfCekBeforeSave()){
            return;
        }
        try {
            Pasien p=new Pasien();
            p.setNorm(txtNorm.getText().equalsIgnoreCase("")? null: txtNorm.getText());
            p.setNama(txtNama.getText());
            p.setAlamatDomisili(txtAlamat.getText());
            p.setTempatLahir(txtTempatLahir.getText());
            p.setTanggalLahir(new SimpleDateFormat("dd-MM-yyyy").parse(txtTglLahir.getText()));
            p.setJenisKelamin(cmbSex.getSelectedItem().toString().substring(0, 1));
            p.setTelepon(txtTelepon.getText());
            p.setHp(txtHp.getText());
            p.setNamaKeluarga(txtNamaKeluarga.getText());
            p.setTeleponKeluarga(txtTelpKeluarga.getText());
            dao.simpan(p);
            if(srcForm==null){
                JOptionPane.showMessageDialog(this, "Simpan pasien sukses!");
            }else if(srcForm instanceof FrmReservasi){
                this.selectedPasien=p;
            }
            this.dispose();
        } catch (ParseException ex) {
            Logger.getLogger(DlgPasien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private PasienDao dao=new PasienDao();

    public void setSrcForm(Object aThis) {
        this.srcForm=aThis;
    }

    public void setTglReservasi(Date date) {
        this.tglReservasi=date;
    }
    
}
