/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgPRUpdateQty.java
 *
 * Created on Aug 1, 2010, 8:27:53 AM
 */

package pembelian;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import main.GeneralFunction;

/**
 *
 * @author cak-ust
 */
public class DlgPRUpdateQty extends javax.swing.JDialog {
    private Connection conn;
    String sPRNo, sKodeBarang;
    private Object srcForm;
    private GeneralFunction fn=new GeneralFunction();
    private double oldQty;
    private int iRow=0, iUpdate=0;


    /** Creates new form DlgPRUpdateQty */
    public DlgPRUpdateQty(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setConn(Connection con){
        this.conn=con;
    }

    public void setSrcForm(Object frm, int row){
        this.srcForm=frm;
        this.iRow=row;
    }

    public void setPR(String sPRNo, String sKodeBarang, String sNamaBarang, double Qty, String satuan){
        lblBarang.setText(sNamaBarang+" ("+sKodeBarang+")");

        this.sPRNo=sPRNo;
        this.sKodeBarang=sKodeBarang;
        this.oldQty=Qty;
        lblSatuanKecil.setText(satuan);
        txtQty.setText(fn.dFmt.format(Qty));
    }

    private void udfSave(){
        if(fn.udfGetDouble(txtQty.getText())==0){
            JOptionPane.showMessageDialog(this, "Masukkan Qty PR dengan nilai diatas Nol!");
            txtQty.requestFocus();
            return;
        }

        try{
            conn.setAutoCommit(false);
            iUpdate=conn.createStatement().executeUpdate("Update phar_pr_detail set jumlah="+fn.udfGetDouble(txtQty.getText())+" " +
                    "where kode_barang='"+sKodeBarang+"' and no_pr='"+sPRNo+"'; ");

            conn.setAutoCommit(true);
            if(srcForm instanceof FrmPRMaintenance ){
                ((FrmPRMaintenance)srcForm).udfLoadPR(iRow);
                
            }
            this.dispose();
            
        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBarang = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblSatuanKecil = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Qty PR");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBarang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBarang.setForeground(new java.awt.Color(0, 0, 153));
        lblBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBarang.setText("jLabel1");
        lblBarang.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblBarang.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 37));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("New Quantity : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 22));

        txtQty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtQty.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQtyFocusGained(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyKeyTyped(evt);
            }
        });
        getContentPane().add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 150, 22));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 90, 30));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 90, 30));

        lblSatuanKecil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lblSatuanKecil, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 70, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 330, 10));

        setSize(new java.awt.Dimension(370, 168));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        udfSave();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyTyped
        fn.keyTyped(evt);
    }//GEN-LAST:event_txtQtyKeyTyped

    private void txtQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyFocusGained
        txtQty.setSelectionStart(0); txtQty.setSelectionEnd(txtQty.getText().length());
    }//GEN-LAST:event_txtQtyFocusGained

    private void txtQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            btnUpdate.requestFocus();
        
    }//GEN-LAST:event_txtQtyKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPRUpdateQty dialog = new DlgPRUpdateQty(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBarang;
    private javax.swing.JLabel lblSatuanKecil;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables

    int getUpdated() {
        return iUpdate;
    }

}
