/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmRptPembelian.java
 *
 * Created on Jul 28, 2010, 1:14:42 PM
 */

package pembelian;

import java.awt.Cursor;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import main.GeneralFunction;
import main.MainForm;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ustadho
 */
public class FrmRptPembelian extends javax.swing.JInternalFrame {
    private Connection conn;
    GeneralFunction fn;

    /** Creates new form FrmRptPembelian */
    public FrmRptPembelian() {
        initComponents();
    }

    public void setConn(Connection con){
        this.conn=con;
    }

    private void udfInitForm(){
        fn=new GeneralFunction(conn);
        jXDatePicker1.setFormats(new String[]{"dd/MM/yyyy"});
        jXDatePicker2.setFormats(new String[]{"dd/MM/yyyy"});
        
    }

    private void udfPrint() {
        try{
            HashMap reportParam = new HashMap();
            JasperReport jasperReport=null;
            DateFormat dformat = new SimpleDateFormat("yyyy-MM-dd");
            String tglAwal = dformat.format(jXDatePicker1.getDate());
            String tglAkhir = dformat.format(jXDatePicker2.getDate());
            String sReport="";
            reportParam.put("corporate", MainForm.sNamaUsaha);
            reportParam.put("alamat", MainForm.sAlamat);
            reportParam.put("telp", "");
            reportParam.put("tanggal1", tglAwal);
            reportParam.put("tanggal2", tglAkhir);
            reportParam.put("supplier", txtSupp.getText());
            reportParam.put("site", txtSite.getText());
            reportParam.put("item", txtSite.getText());
            reportParam.put("consigment", chkKonsinyasi.isSelected());
            reportParam.put("bp_type", cmbItemType.getSelectedIndex()==0? "": cmbItemType.getSelectedItem().toString().substring(0, 1));

            switch (jList1.getSelectedIndex()){
                case 0:{sReport="PR_PerHari";       break;}
                case 1:{sReport="PO_RekapBySite";   break;}
                case 2:{sReport="PO_BySuppDetail";  break;}
                case 3:{sReport="PO_BySuppRekap";   break;}
                case 4:{sReport="PO_WithTTB_Rekap"; break;}
                case 5:{sReport="PO_BySiteRekap";   break;}
                case 6:{sReport="GR_BySuppRekap";   break;}
                case 7:{sReport="Pembelian_10_BesarBySupp";   break;}
                case 8:{sReport="GR_TotalItemPerSupp"; break;}
                case 9:{sReport="GR_BpTypeDetail";  break;}
                case 10:{sReport="POCash_Rekap";     break;}
                case 11:{sReport="PO_Outstanding";     break;}
                default:{
                    break;
                }
            }
            if(sReport.length()==0){
                JOptionPane.showMessageDialog(this, "Report tidak ditemukan!");
                return ;
            }
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            //System.out.println(getClass().getResourceAsStream("Reports/"+sReport+".jasper"));
            jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResourceAsStream("Reports/"+sReport+".jasper"));
            JasperPrint print = JasperFillManager.fillReport(jasperReport,reportParam,conn);
            print.setOrientation(jasperReport.getOrientationValue());
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            if(print.getPages().isEmpty())
                JOptionPane.showMessageDialog(this, "Report tidak ditemukan!");
            else
                JasperViewer.viewReport(print,false);

        }
        catch(JRException je){System.out.println(je.getMessage());}
        //catch(NullPointerException ne){JOptionPane.showMessageDialog(null, ne.getMessage(), MainForm.sMessage, JOptionPane.OK_OPTION);}

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jLabel17 = new javax.swing.JLabel();
        txtSite = new javax.swing.JTextField();
        lblSite = new javax.swing.JLabel();
        chkKonsinyasi = new javax.swing.JCheckBox();
        lblItemType = new javax.swing.JLabel();
        txtSupp = new javax.swing.JTextField();
        lblSupp = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cmbItemType = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Laporan Pembelian & Inventory");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1.  Purchase Requistion", "2.  Purhcase Order (Rekap)", "3.  Purchase Order By Supplier (Detail)", "4.  Purchase Order By Supplier (Rekap)", "5.  Purchase Order With Tgl TTB (Rekap)", "6.  Purchase Order By Site", "7.  Good Receipt by date and Supplier (Rekap)", "8.  Laporan Pembelian 10 Besar / Supplier", "9.  Total Item Good Receipt (TTB) Per Supplier", "10. Laporan Pembelian (Detail)", "11. Rekapitulasi PO Cash", "12. PO Outstanding" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 350, 300));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXDatePicker1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Tanggal Awal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tanggal Akhir");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 20));

        jXDatePicker2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jXDatePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 140, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Site ID");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 20));

        txtSite.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtSite.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSite.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtSite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSiteFocusLost(evt);
            }
        });
        txtSite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSiteKeyReleased(evt);
            }
        });
        jPanel1.add(txtSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 50, 20));

        lblSite.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblSite.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblSite.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblSitePropertyChange(evt);
            }
        });
        jPanel1.add(lblSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 190, 20));

        chkKonsinyasi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkKonsinyasi.setText(" Konsinyasi");
        jPanel1.add(chkKonsinyasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, -1));

        lblItemType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblItemType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblItemType.setText("Item Type");
        jPanel1.add(lblItemType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 20));

        txtSupp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtSupp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSupp.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtSupp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSuppFocusLost(evt);
            }
        });
        txtSupp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuppKeyReleased(evt);
            }
        });
        jPanel1.add(txtSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 145, 50, 20));

        lblSupp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblSupp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblSupp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblSuppPropertyChange(evt);
            }
        });
        jPanel1.add(lblSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 145, 190, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Supplier");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 145, 90, 20));

        cmbItemType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbItemType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<All>", "Medical", "Supplies" }));
        jPanel1.add(cmbItemType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 370, 300));

        jButton1.setText("Preview");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 90, 30));

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSiteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSiteFocusLost
        // TODO add your handling code here:
}//GEN-LAST:event_txtSiteFocusLost

    private void txtSiteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSiteKeyReleased
        String sQry="";
        if(jList1.getSelectedIndex()==11) //Nama barang
            sQry="select kode_barang, coalesce(nama_barang,'') as nama_barang from phar_item " +
                "where upper(kode_barang||coalesce(nama_barang,'')) iLike upper('%" + txtSite.getText() +"%') order by 2";
        else
            sQry="select site_id, coalesce(site_name,'') as site_name from phar_site " +
                "where upper(site_id||coalesce(site_name,'')) iLike upper('%" + txtSite.getText() +"%') order by 2";
        
        fn.lookup(evt, new Object[]{lblSite}, sQry, txtSite.getWidth()+lblSite.getWidth(), 300);
}//GEN-LAST:event_txtSiteKeyReleased

    private void lblSitePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblSitePropertyChange
        // TODO add your handling code here:
}//GEN-LAST:event_lblSitePropertyChange

    private void txtSuppFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSuppFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuppFocusLost

    private void txtSuppKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuppKeyReleased
        fn.lookup(evt, new Object[]{lblSupp},
                "select kode_supplier as kode, coalesce(nama_supplier,'') as supplier from phar_supplier " +
                "where upper(kode_supplier||coalesce(nama_supplier,'')) Like upper('%" + txtSupp.getText() +"%') order by 2",
                txtSupp.getWidth()+lblSupp.getWidth()+15, 300);
    }//GEN-LAST:event_txtSuppKeyReleased

    private void lblSuppPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblSuppPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSuppPropertyChange

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        udfInitForm();
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        udfPrint();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        lblItemType.setVisible(jList1.getSelectedIndex()==9);
        cmbItemType.setVisible(jList1.getSelectedIndex()==9);
        jLabel17.setText(jList1.getSelectedIndex()==11? "Item": "Site ID");
    }//GEN-LAST:event_jList1ValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkKonsinyasi;
    private javax.swing.JComboBox cmbItemType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JLabel lblItemType;
    private javax.swing.JLabel lblSite;
    private javax.swing.JLabel lblSupp;
    private javax.swing.JTextField txtSite;
    private javax.swing.JTextField txtSupp;
    // End of variables declaration//GEN-END:variables

}
